name: Extract Production Orgs in Custom YAML Format

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Download altinn-orgs.json
        run: curl -sSL -o altinn-orgs.json https://altinncdn.no/orgs/altinn-orgs.json

      - name: Extract and format production orgs to valid YAML
        run: |
          echo "sites:" > sites.yml
          jq -r '
            .orgs | to_entries[]
            | select(.value.environments != null and (.value.environments | index("production")))
            | (
                "  - name: \(.key)\n" +
                "    url: https://\(.key).apps.altinn.no/kuberneteswrapper/api/v1/deployments" +
                (
                  if (.value.logo // "") != ""
                  then "\n    icon: \(.value.logo)"
                  else ""
                  end
                )
              )
          ' altinn-orgs.json >> sites.yml

      - name: Show final YAML
        run: cat sites.yml
